find_path(NECLATENT1_DIR include/LatentEFS.h ${CMAKE_SOURCE_DIR}/3rdparty/*)

set(NECLATENT1_SUBDIR /win/${BITNESS})
set(NECLATENT1_LIB_DIR ${NECLATENT1_DIR}/lib${NECLATENT1_SUBDIR})
set(NECLATENT1_BIN_DIR ${NECLATENT1_DIR}/bin${NECLATENT1_SUBDIR})

include_directories(${NECLATENT1_DIR}/include)
link_directories(${NECLATENT1_LIB_DIR})

if(MSVC)
  file(GLOB NECLATENT1_LIBS ${NECLATENT1_LIB_DIR}/*.lib)
else()
  file(GLOB NECLATENT1_LIBS ${NECLATENT1_BIN_DIR}/*.dll)
endif()
