set(CTEST_PROJECT_NAME ${CPACK_PACKAGE_NAME})
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

if(NOT DEFINED CTEST_DROP_METHOD)
  set(CTEST_DROP_METHOD "http")
endif()

if(CTEST_DROP_METHOD STREQUAL "http")
  set(CTEST_DROP_SITE "my.cdash.org")
  set(CTEST_DROP_LOCATION "/submit.php?project=OpenBR")
  set(CTEST_DROP_SITE_CDASH TRUE)
endif(CTEST_DROP_METHOD STREQUAL "http")
