set(BR_WITH_DLIB OFF CACHE BOOL "Build with DLib")

if(${BR_WITH_DLIB})
  find_package(DLib REQUIRED)
  add_definitions(-DDLIB_NO_GUI_SUPPORT)
  set(BR_THIRDPARTY_SRC ${BR_THIRDPARTY_SRC} ${DLib_DIR}/dlib/all/source.cpp)
  install(DIRECTORY ${DLib_DIR}/models/ DESTINATION share/openbr/models/dlib)
else()
  set(BR_EXCLUDED_PLUGINS ${BR_EXCLUDED_PLUGINS} plugins/classification/dlib.cpp)
endif()
