set(BR_WITH_PP4 OFF CACHE BOOL "Build with PittPatt 4")

if(${BR_WITH_PP4})
  find_package(PP4 REQUIRED)
  set(BR_THIRDPARTY_LIBS ${BR_THIRDPARTY_LIBS} ${PP4_LIBS})
  install(DIRECTORY ${PP4_DIR}/lib/ DESTINATION lib)
  install(DIRECTORY ${PP4_DIR}/models/ DESTINATION models/pp4)
else()
  set(BR_EXCLUDED_PLUGINS ${BR_EXCLUDED_PLUGINS} plugins/classification/pp4.cpp)
endif()
