set(BR_WITH_NECLATENT1 OFF CACHE BOOL "Build with NEC Latent SDK 1")

if(${BR_WITH_NECLATENT1})
  find_package(NECLATENT1 REQUIRED)
  set(BR_THIRDPARTY_SRC ${BR_THIRDPARTY_SRC} plugins/neclatent1.cpp)
  set(BR_THIRDPARTY_LIBS ${BR_THIRDPARTY_LIBS} ${NECLATENT1_LIBS})
  install(DIRECTORY ${NECLATENT1_BIN_DIR}/ DESTINATION bin)
endif()
